spring:
  profiles.active: ${stage:dev}

guest.info:
  url: https://gist.githubusercontent.com/fjahr/b164a446db285e393d8e4b36d17f4143/raw/75108c09a72a001a985d27b968a0ac5a867e830b/smarthost_hotel_guests.json
  file: src/main/resources/hotel_guests.json

premium.threshold: 100.00
